### ISSUE TITLE
TypeError: unhashable type: 'numpy.ndarray'

### ISSUE THREAD

**Issue by alexey-krasnov** [dmw51/reactiondataextractor2#1]
Deat @dmw51 
I tried to run the code according to the provided instructions in the conda environment with Python 3.8.17 on osx-arm64:

`python reactiondataextractor/extract.py --path ../Benchmark/310002189885.png`

and I encountered the following Error. Here is the output in Terminal:

**TensorFlow Addons (TFA) has ended development and introduction of new features.
TFA has entered a minimal maintenance and release mode until a planned end of life in May 2024.
Please modify downstream libraries to take dependencies from other repositories in our TensorFlow community (e.g. Keras, Keras-CV, and Keras-NLP). 

For more information see: https://github.com/tensorflow/addons/issues/2807 

  warnings.warn(
number of potential arrow crops: 64
number of potential arrow crops: 34
Traceback (most recent call last):
  File "reactiondataextractor/extract.py", line 42, in <module>
    extractor.extract()
  File "ReactionDataExtractor/reactiondataextractor2/reactiondataextractor/extractors/scheme_extractor.py", line 64, in extract
    scheme = self.extract_from_image(self.path)
  File "ReactionDataExtractor/reactiondataextractor2/reactiondataextractor/extractors/scheme_extractor.py", line 119, in extract_from_image
    smiles_extractor.extract()
  File "ReactionDataExtractor/reactiondataextractor2/reactiondataextractor/extractors/smiles.py", line 28, in extract
    self.recognise(diag)
  File "ReactionDataExtractor/reactiondataextractor2/reactiondataextractor/extractors/smiles.py", line 42, in recognise
    predicted_SMILES = self.recogniser.detokenize_output(predicted_tokens)
  File "ReactionDataExtractor/reactiondataextractor2/reactiondataextractor/recognise.py", line 66, in detokenize_output
    outputs = [tokenizer.index_word[i] for i in predicted_array[0].numpy()]
  File "ReactionDataExtractor/reactiondataextractor2/reactiondataextractor/recognise.py", line 66, in <listcomp>
    outputs = [tokenizer.index_word[i] for i in predicted_array[0].numpy()]
TypeError: unhashable type: 'numpy.ndarray'**

Attached please find the image that I tried to recognize, however for other images the problem persists regardless image format or quality.
![310002189885](https://github.com/dmw51/reactiondataextractor2/assets/58355615/96896a9e-3fbd-4293-b4e9-e0ed3147c4f4)

**Comment by dmw51** [comment]
Hi,

Unfortunately, I'm unable to reproduce this issue, as the example image runs without errors.

I have fixed documentation detokenize_output in recognise.py. The input should be a Tensor of shape [1, n_tokens], hence the iteration runs through the n_tokens dimension. If the shape doesn't match, an array is passed, which raises the unhashable type exception.

To make this slightly more robust, I have made a change from indexing the Tensor to squeezing it to remove any other dimensions of size 1, but it will be challenging to debug further. Let me know if this helps.
